# Site specific settings
title: "lostcarrier"
name: "lostcarrier"
keywords: "lostcarrier"
baseurl: ""
url: "https://lostcarrier.github.io"
description: "lostcarrier"
fanpage_id: ""
excerpt_separator: <!--more-->

# Site general settings
lang: "en"
ssl: true # It will redirect to https

# Media
# Just the shortname:
twitter: lostcarri3r 
github: lostcarrier 

# Build settings
markdown: kramdown
syntax_highlighter: rouge
highlighter: rouge
permalink: /:categories/:title/
