# Site specific settings
title: "lostcarrier"
name: "lostcarrier"
keywords: "lostcarrier"
baseurl: ""
url: "https://lostcarrier.github.io"
description: "lostcarrier"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
ssl: true # It will redirect to https

# Media
# Just the shortname:
disqus: test
twitter: lostcarri3r 
github: lostcarrier 

# Build settings
markdown: kramdown
permalink: /:categories/:title/
